doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 80
autodetect: yes

dodgy:
  run: no

pylint:
  disable:
    - unused-variable
    - too-many-arguments
    - star-args
    - C0325